name: flutter_env_config
description: "A Flutter package to manage environment-specific configurations using a JSON file. Easily load and access different settings based on the target environment (e.g., dev, staging, prod)."
version: 1.0.0
license: MIT
homepage: https://github.com/Atanu-Sabyasachi/flutter_env_config
repository: https://github.com/Atanu-Sabyasachi/flutter_env_config
funding:
  - https://buymeacoffee.com/atanusabyasachi

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.3
  build_runner: ^2.4.14
  yaml_writer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
executables:
  generate-config: "bin/generate_config.dart"

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/config.yaml



